<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <PackageReference Include="Azure.Identity" />
    <PackageReference Include="Microsoft.Agents.AI" />
    <PackageReference Include="OpenAI" />
    <ProjectReference Include="..\Defra.Contracts\Defra.Contracts.csproj" />
    <ProjectReference Include="..\Defra.Policy\Defra.Policy.csproj" />
  </ItemGroup>

  <PropertyGroup>
  </PropertyGroup>

</Project>
